version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mottu_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
